server:
  port: 1234

spring:
  datasource:
    username: ICAT
    password: ICAT
    url: jdbc:mysql://122.152.202.227:3306/catManagement?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  redis:
    database: 0
    host: 122.152.202.227
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 10000ms
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      # 映射规则，有两种规则，physical：使用驼峰命名,implict: 使用下划线命名
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: backend.pojo
  mapper-locations: classpath*:mapper/*Mapper.xml